# Site settings
title: XYF Blog
SEOTitle: 向雨菲的博客 | XYF Blog
header-img: img/post-bg-desk.jpg
email: 502022370053@smail.nju.edu.cn
description: "A student in Nanjing University."
keyword: "XYF, AI, NJU"
url: "https://yufei-xiang.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Yufei-Xiang/Yufei-Xiang.github.io.git" # you code repository
